version: "3.7"

x-general_config: &general_config
  working_dir: /go/src
  volumes:
    - .:/go/src
    - /etc/passwd:/etc/passwd:ro
    - /etc/group:/etc/group:ro
    - ./.go_build/cache:/tmp/.cache
    - ./.go_build/pkg:/go/pkg
  environment:
    - HOME=/tmp

services:
  go:
    <<: *general_config
    build:
      dockerfile: Dockerfile
      target: base
    entrypoint: go
  goreleaser:
    <<: *general_config
    build:
      dockerfile: Dockerfile
      target: releaser
    entrypoint: goreleaser
