name: build CLI tool written in Go & release to the GitHub Release

on:
  workflow_dispatch:
    inputs:
      method:
        description: |
          Specify semantic versioning which you want to release.
          (version would be incremented depending on the specified semantic versioning.)
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GHA_GO_VERSION_SEMVAR: '^1.22.0'
    steps:
    - name: Check Actor & Branch
      if: github.actor != 'at0x0ft' || github.ref != github.ref != 'refs/heads/main'
      run: exit 1

    - name: Wait for CI status
      id: ci_result
      uses: Sibz/await-status-action@v1.0.2
      with:
        contexts: ci_status
        authToken: ${{ secrets.GITHUB_TOKEN }}
        timeout: 30
    - name: Check CI result
      if: steps.ci_result.outputs.result != 'success'
      run: |
        printf 'failed check name: "%s"' ${{ steps.ci_result.outputs.failedCheckNames }}
        printf '           states: "%s"' ${{ steps.ci_result.outputs.failedCheckStates }}
        exit 1

    - uses: actions/checkout@v3
    - name: Bump-up semantic version
      id: vertag
      uses: kyoh86/git-vertag-action@v1.1
      with:
        method: "${{ github.event.inputs.method }}"

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GHA_GO_VERSION_SEMVAR }}
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
