name: CI for Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/base

    - name: Test
      run: go test -v ./...

    - name: lint
      uses: reviewdog/action-golangci-lint@v2
      with:
        golang_ci_lint_flags: "--enable-all --exclude-use-default=false"
        go_version: ${{ jobs.base.env.GHA_GO_VERSION_SEMVAR }}
