name: CI for Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GHA_GO_VERSION_SEMVAR: '^1.22.0'
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GHA_GO_VERSION_SEMVAR }}

    - name: Test
      run: make ci_test

    - name: lint
      uses: reviewdog/action-golangci-lint@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        golang_ci_lint_flags: " --skip-dirs=.go_build,.git --enable-all --exclude-use-default=false"
        go_version: ${{ env.GHA_GO_VERSION_SEMVAR }}

    - name: format
      run: make ci_format
